plugin:
    name: 'crydesign.socializer::lang.plugin.name'
    description: 'crydesign.socializer::lang.plugin.description'
    author: DmitryBykov
    icon: oc-icon-share-alt
    homepage: 'https://github.com/Cryden/oc-socializer'
navigation:
    main-menu-item:
        label: Cross
        url: crydesign/socializer/crosspostings
        icon: icon-adn
