plugin:
    name: 'crydesign.socializer::lang.plugin.name'
    description: 'crydesign.socializer::lang.plugin.description'
    author: CRYDEsigN
    icon: oc-icon-share-alt
    homepage: 'https://github.com/Cryden/oc-socializer'
